# The west manifest file (west.yml) for the nRF Connect SDK (NCS).
#
# The per-workspace west configuration file, ncs/.west/config,
# specifies the location of this manifest file like this:
#
#     [manifest]
#     path = nrf
#
# See the west documentation for more information:
#
# https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/guides/west/index.html

manifest:
  version: "0.13"

  # "remotes" is a list of locations where git repositories are cloned
  # and fetched from.
  remotes:
    # nRF Connect SDK GitHub organization.
    # NCS repositories are hosted here.
    - name: ncs
      url-base: https://github.com/nrfconnect
    # Third-party repository sources:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: throwtheswitch
      url-base: https://github.com/ThrowTheSwitch
    - name: armmbed
      url-base: https://github.com/ARMmbed
    - name: nordicsemi
      url-base: https://github.com/NordicSemiconductor
    - name: dragoon
      url-base: https://projecttools.nordicsemi.no/bitbucket/scm/drgn
    - name: memfault
      url-base: https://github.com/memfault
    - name: ant-nrfconnect
      url-base: https://github.com/ant-nrfconnect
    - name: babblesim
      url-base: https://github.com/BabbleSim
    - name: moi
      url-base: git@github.com:nordicjm

  # If not otherwise specified, the projects below should be obtained
  # from the ncs remote.
  defaults:
    remote: ncs

  group-filter: [-homekit, -nrf-802154, -dragoon, -find-my, -ant, -babblesim]

  # "projects" is a list of git repositories which make up the NCS
  # source code.
  #
  # For 'userdata' fields in the projects area, please refer to:
  # https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/dm_code_base.html
  projects:

    - name: NOPE
#      repo-path: NOPE.git
      repo-path: sdk-nrf-next.git
      path: NOPE
      remote: moi
      revision: other
    # The Zephyr RTOS fork in the NCS, along with the subset of its
    # modules which NCS imports directly.
    #
    # https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/introduction/index.html
    # https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/guides/modules.html
    - name: zephyr
      repo-path: sdk-zephyr
      revision: 74c7bca86e6a7d590333681eef90e159d79bcfe8
      import:
        # In addition to the zephyr repository itself, NCS also
        # imports the contents of zephyr/west.yml at the above
        # revision. Only the projects explicitly named in the
        # following allowlist are imported.
        #
        # Note that the zephyr west extensions (like 'build', 'flash',
        # 'debug', etc.) are automatically provided by this import, so
        # there's no need to add a redundant west-commands: key for
        # the zephyr project.
        #
        # Please keep this list sorted alphabetically.
        name-allowlist:
          - cmsis
          - hal_nordic
          - libmetal
          - open-amp
          - segger
          - tinycrypt
          - zcbor

    # NCS repositories.
    #
    # Some of these are also Zephyr modules which have NCS-specific
    # changes.
    - name: hostap
      repo-path: sdk-hostap
      path: modules/lib/hostap
      revision: ff98ecf541f1e43a9e89e4d47f24e7c59c65f5fe
      userdata:
        ncs:
          upstream-url: https://w1.fi/cgit/hostap/
          upstream-sha: e792f38db8471f35ee94f109a4093dece8f78c6a
          compare-by-default: false
    - name: mcuboot
      repo-path: sdk-mcuboot
      revision: c78d59dbe8ec48cfbdff9a0bfc12f25b90c73d2f
      path: bootloader/mcuboot
    - name: mbedtls
      path: modules/crypto/mbedtls
      repo-path: sdk-mbedtls
      revision: 3c2bc903cb396af6033115c8186f0807ef81bdaf
    - name: nrfxlib
      repo-path: sdk-nrfxlib
      path: nrfxlib
      revision: 9cb73143fb543d3eefeeb356ae335a7e4c756512
    - name: qcbor
      url: https://github.com/laurencelundblade/QCBOR.git
      revision: b0e7033268e88c9f27146fa9a1415ef4c19ebaff
      path: modules/tee/tf-m/qcbor
    - name: trusted-firmware-m
      repo-path: sdk-trusted-firmware-m
      path: modules/tee/tf-m/trusted-firmware-m
      revision: ab8140dd25da98356619ae7ed02b735404c5b962
    - name: matter
      repo-path: sdk-connectedhomeip
      path: modules/lib/matter
      revision: 032a0a95c5b6c761b35cd73e98e41f56f59fa5f0
      userdata:
        ncs:
          upstream-url: https://github.com/project-chip/connectedhomeip
          upstream-sha: 4088a77f557e8571a39338fad51a1d8eb0131d79
          compare-by-default: false
      submodules:
        - name: nlio
          path: third_party/nlio/repo
        - name: nlassert
          path: third_party/nlassert/repo
        - name: nlunit-test
          path: third_party/nlunit-test/repo
        - name: pigweed
          path: third_party/pigweed/repo
    - name: nrf-802154
      repo-path: sdk-nrf-802154
      path: nrf-802154
      revision: 2e0320844049e041de9d5769d810c5a15b10842a
      groups:
        - nrf-802154
    - name: cjson
      repo-path: sdk-cjson
      path: modules/lib/cjson
      revision: c6af068b7f05207b28d68880740e4b9ec1e4b50a
      userdata:
        ncs:
          upstream-url: https://github.com/DaveGamble/cJSON
          upstream-sha: d2735278ed1c2e4556f53a7a782063b31331dbf7
          compare-by-default: false
    - name: openthread
      repo-path: sdk-openthread
      path: modules/lib/openthread
      revision: 2c8a0af24433dd802414ae1832a3f3e5948514b7
      userdata:
        ncs:
          upstream-url: https://github.com/openthread/openthread
          upstream-sha: 55074652907295709f9f3361244a6e76f732bcba
          compare-by-default: false

  # West-related configuration for the nrf repository.
  self:
    # This repository should be cloned to ncs/nrf.
    path: nrf
    # This line configures west extensions.
    west-commands: scripts/west-commands.yml
